FROM debian:stretch-slim

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y unixodbc unixodbc-dev libboost-all-dev python-virtualenv cmake g++ wget \
                       odbc-postgresql ninja-build gnupg apt-transport-https && \
    apt-get clean

# install the mysql odbc driver:
RUN wget https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.15-linux-debian9-x86-64bit.tar.gz && \
    tar xzf mysql-connector-odbc-8.0.15-linux-debian9-x86-64bit.tar.gz && \
    /mysql-connector-odbc-8.0.15-linux-debian9-x86-64bit/bin/myodbc-installer -d -a -n MySQL -t DRIVER=`ls /mysql-*/lib/libmyodbc*w.so`

# install the mssql odbc driver:
RUN wget https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add - && \
    wget https://packages.microsoft.com/config/debian/9/prod.list -O- > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install msodbcsql17 && \
    odbcinst -i -d -f /opt/microsoft/msodbcsql17/etc/odbcinst.ini


# create a python virtualenv at /venv that contains the necessary build and test packages:
RUN virtualenv --python=python3.5 /venv && \
    /venv/bin/pip install numpy==1.16.1 pandas==0.24.1 pytest mock pytest-cov


# set locale to utf-8, which is required for some odbc drivers (mysql);
# also, set environment as set after 'source /venv/bin/activate'
ENV LC_ALL=C.UTF-8 VIRTUAL_ENV=/venv PATH=/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
