version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=pg_pwd!
      - POSTGRES_DB=test_db
    ports:
     - "5432"

  mssql:
    build:
      context: .
      dockerfile: Dockerfile-mssql
    ports:
      - "1433"

  mysql:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=MysqlPassword
        - MYSQL_DATABASE=test_db
      ports:
        - "3306"

  turbodbc:
    build:
      context: .
      dockerfile: Dockerfile-turbodbc
    environment:
       - ODBCINI=/turbodbc/contrib/docker/odbc.ini
       - PYTHONPATH=/turbodbc/build_docker
       # configure turbodbc tests to run against all of the above databases;
       # adapt manually if needed:
       - TURBODBC_TEST_CONFIGURATION_FILES=query_fixtures_mysql.json,query_fixtures_postgres.json,query_fixtures_mssql.json
    volumes:
       - ../..:/turbodbc
