version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=pg_pwd!
      - POSTGRES_DB=test_db
    ports:
     - "5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword1
    ports:
      - "1433"

  mysql:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=MysqlPassword
        - MYSQL_DATABASE=test_db
      ports:
        - "3306"

  turbodbc:
    build:
      context: .
    environment:
       - ODBCINI=/turbodbc/contrib/docker/odbc.ini
       - PYTHONPATH=/turbodbc/build_docker
       - TURBODBC_TEST_CONFIGURATION_FILES
    volumes:
       - ../..:/turbodbc
